base_url = "https://capra.cs.cornell.edu/latte26/"
compile_sass = false
build_search_index = false

# Don't refuse to compile when we refer to generated anchors.
[link_checker]
internal_level = "warn"

[extra]
title = "LATTE â€™26"
